./starfield_cuda
./starfield_cuda
./starfield_cuda
./starfield_cuda
./starfield_cuda
./starfield_cuda
./starfield_cuda
./starfield_cuda
./starfield_cuda
./starfield_cuda
./starfield_cuda
./starfield_cuda
./starfield_cuda
./starfield_cuda
./starfield_cuda
./starfield_cuda
./starfield_cuda
